---
#-------------------------------
# General Site Settings
title: Tom Arra
logo: # You can add own logo. For example '/images/logo.png'.
description: Thoughts, stories and ideas. Mostly.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomarra.com" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Tom Arra
  avatar: "/images/headshot.jpg"

social:
  - { icon: "fa-twitter", label: Twitter, link: "https://twitter.com/tom_arra" }
  - {
      icon: "fa-bluesky",
      label: Bluesky,
      link: "https://bsky.app/profile/tomarra.com",
    }
  - {
      icon: "fa-mastodon",
      label: Mastodon,
      link: "https://mastodon.social/@tomarra",
    }
  - {
      icon: "fa-facebook",
      label: Facebook,
      link: "https://www.facebook.com/tomarra",
    }
  - {
      icon: "fa-instagram",
      label: Instagram,
      link: "https://www.instagram.com/tom_arra",
    }
  - { icon: "fa-github", label: GitHub, link: "https://github.com/tomarra" }
  - {
      icon: "fa-linkedin",
      label: LinkedIn,
      link: "https://www.linkedin.com/in/tomarra/",
    }
  - {
      icon: "fa-flickr",
      label: Flickr,
      link: "https://www.flickr.com/people/tomarra/",
    }
  - { icon: "fa-youtube", label: GitHub, link: "https://youtube.com/@tomarra" }

#-------------------------------
# Hero Settings
hero:
  hero__title: Hey, Iâ€™m Tom! Product Leader & Engineer.
  hero__description: I'm a product leader & engineer who loves to work with global teams and products. I help organize the corporate chaos to make the best solutions for customers. Here I post about not just tech but a few hobbies as well.
  hero__image: "/images/headshot.jpg"

#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:year/:month/:day/:title:output_ext
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed
